//! Renders a [`Schema`] as the human-readable `SCHEMA.md`.
//!
//! The generated file is what a person or an agent reads before writing a note,
//! so it carries the prose arguments as well as the field table. Keeping both in
//! the data file is what stops the document and the linter disagreeing -- which
//! they will, silently, the first time only one of them is updated.

use std::fmt::Write as _;

use crate::{Check, Field, Fix, Kind, Rule, SECTIONS, Schema, Section, Severity};

const BANNER: &str =
    "<!-- GENERATED by `kb schema render`. Edit schemas/note.toml, not this file. -->";

pub fn render_markdown(schema: &Schema) -> String {
    let mut out = String::new();

    writeln!(out, "{BANNER}\n").unwrap();
    writeln!(out, "# {}\n", schema.schema.title).unwrap();

    let preamble = schema.schema.preamble.trim();
    if !preamble.is_empty() {
        writeln!(out, "{preamble}\n").unwrap();
    }

    for section in SECTIONS {
        match section {
            "frontmatter" => render_frontmatter(&mut out, schema),
            "rules" => render_rules(&mut out, schema, "Rules", "rules"),
            "links" => render_rules(&mut out, schema, "Links", "links"),
            _ => unreachable!("SECTIONS and the renderer must agree"),
        }
        for extra in schema.sections_after(section) {
            render_section(&mut out, extra);
        }
    }

    out
}

fn render_frontmatter(out: &mut String, schema: &Schema) {
    writeln!(out, "## Frontmatter\n").unwrap();
    writeln!(out, "```yaml\n---").unwrap();
    for field in &schema.field {
        writeln!(out, "{}", example_line(field)).unwrap();
    }
    writeln!(out, "---\n```\n").unwrap();

    writeln!(out, "| Field | Required | Values |").unwrap();
    writeln!(out, "| ----- | -------- | ------ |").unwrap();
    for field in &schema.field {
        writeln!(
            out,
            "| `{}` | {} | {} |",
            field.name,
            if field.required { "yes" } else { "no" },
            escape_cell(&values_cell(field)),
        )
        .unwrap();
    }
    out.push('\n');

    for rule in schema.rules_in("frontmatter") {
        render_rule(out, rule);
    }
}

/// A sample value, so the block above the table reads as a real note rather than
/// a list of type names.
fn example_line(field: &Field) -> String {
    match field.kind {
        Kind::Enum => format!("{}: {}", field.name, field.values.first().map_or("", |v| v)),
        Kind::Date => format!("{}: 2026-08-30", field.name),
        Kind::Pattern => format!("{}: global", field.name),
        Kind::List => format!("{}:\n  - ...", field.name),
        Kind::Text => format!("{}: ...", field.name),
    }
}

fn values_cell(field: &Field) -> String {
    match field.kind {
        Kind::Enum => {
            let values = field
                .values
                .iter()
                .map(|v| format!("`{v}`"))
                .collect::<Vec<_>>()
                .join(" ");
            join_doc(&values, &field.doc)
        }
        Kind::Pattern => {
            // Alternatives get one code span each rather than one span holding
            // the pipes: it reads better, and a bare `|` in a table cell splits
            // the row.
            let shape = field
                .pattern
                .as_deref()
                .unwrap_or_default()
                .split('|')
                .map(|alt| format!("`{}`", alt.trim()))
                .collect::<Vec<_>>()
                .join(", ");
            join_doc(&shape, &field.doc)
        }
        Kind::List => {
            let shape = match field.min {
                Some(min) if min > 0 => format!("list, at least {min}"),
                _ => "list".to_string(),
            };
            join_doc(&shape, &field.doc)
        }
        Kind::Text | Kind::Date => field.doc.trim().to_string(),
    }
}

/// A `|` anywhere in a table cell ends the cell, so any that survive the shapes
/// above -- from a doc string, say -- must be escaped.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn join_doc(shape: &str, doc: &str) -> String {
    let doc = doc.trim();
    if doc.is_empty() {
        shape.to_string()
    } else {
        format!("{shape} \u{2014} {doc}")
    }
}

fn render_rules(out: &mut String, schema: &Schema, heading: &str, section: &str) {
    writeln!(out, "## {heading}\n").unwrap();
    for rule in schema.rules_in(section) {
        render_rule(out, rule);
    }
}

fn render_rule(out: &mut String, rule: &Rule) {
    writeln!(out, "**{}**{}", rule.title, annotation(rule)).unwrap();
    let doc = rule.doc.trim();
    if !doc.is_empty() {
        writeln!(out, "\n{doc}").unwrap();
    }
    out.push('\n');
}

/// What the tool will actually do about a violation. Stated on every rule so a
/// reader never has to guess whether "must" means "lint fails" or "be careful".
fn annotation(rule: &Rule) -> String {
    let applies = if rule.applies_to.is_empty() {
        String::new()
    } else {
        let types = rule
            .applies_to
            .iter()
            .map(|t| format!("`{t}`"))
            .collect::<Vec<_>>()
            .join(", ");
        format!("{types} only; ")
    };

    let verdict = match (rule.check, rule.severity, rule.fix) {
        (Check::None, _, _) => "not mechanically checked".to_string(),
        (_, Severity::Error, Fix::Fix) => "lint repairs it where it can, else fails".to_string(),
        (_, Severity::Error, Fix::Report) => "lint fails".to_string(),
        (_, Severity::Warn, Fix::Fix) => "lint repairs it where it can, else warns".to_string(),
        (_, Severity::Warn, Fix::Report) => "lint warns".to_string(),
    };

    format!(" _({applies}{verdict})_")
}

fn render_section(out: &mut String, section: &Section) {
    writeln!(out, "## {}\n", section.title).unwrap();
    let doc = section.doc.trim();
    if !doc.is_empty() {
        writeln!(out, "{doc}\n").unwrap();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn rendered() -> String {
        let schema = Schema::load(Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../schemas/note.toml"
        )))
        .unwrap();
        render_markdown(&schema)
    }

    #[test]
    fn output_says_it_is_generated() {
        assert!(rendered().starts_with(BANNER));
    }

    #[test]
    fn every_field_reaches_the_table() {
        let out = rendered();
        for name in [
            "description",
            "type",
            "scope",
            "confidence",
            "asserted",
            "source",
            "triggers",
        ] {
            assert!(out.contains(&format!("| `{name}` |")), "missing {name}");
        }
    }

    /// The discriminating case: `scope`'s shape is the one field whose value
    /// contains the table's own delimiter, so a renderer that forgets to handle
    /// it produces a table that still looks plausible and is silently wrong.
    #[test]
    fn a_pipe_in_a_value_does_not_split_the_row() {
        let out = rendered();
        let row = out
            .lines()
            .find(|l| l.starts_with("| `scope`"))
            .expect("scope row");
        assert_eq!(
            row.matches(" | ").count(),
            2,
            "scope row has extra cells: {row}"
        );
        assert!(row.contains("`project:NAME`"), "{row}");
    }

    #[test]
    fn every_rule_reaches_the_document() {
        let schema = Schema::load(Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../schemas/note.toml"
        )))
        .unwrap();
        let out = render_markdown(&schema);
        for rule in &schema.rule {
            assert!(out.contains(&rule.title), "rule `{}` was dropped", rule.id);
        }
    }

    /// The discriminating case: a rule stated for the writer must read
    /// differently from one the tool enforces, or the document quietly promises
    /// enforcement that does not exist.
    #[test]
    fn unenforceable_rules_read_differently_from_enforced_ones() {
        let out = rendered();
        let one_concept = out
            .lines()
            .find(|l| l.contains("One concept per note"))
            .expect("rule present");
        let links = out
            .lines()
            .find(|l| l.contains("must resolve"))
            .expect("rule present");
        assert!(
            one_concept.contains("not mechanically checked"),
            "{one_concept}"
        );
        assert!(links.contains("lint repairs it where it can"), "{links}");
    }

    #[test]
    fn prose_sections_land_after_the_section_they_follow() {
        let out = rendered();
        let body = out.find("## Body").expect("body section");
        let rules = out.find("## Rules").expect("rules section");
        let detectability = out.find("## On rules").expect("detectability section");
        assert!(body < rules, "Body follows frontmatter, so precedes Rules");
        assert!(rules < detectability, "detectability follows Rules");
    }
}
